# Generated by Django 4.2.11 on 2024-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='membership',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='orders',
            name='supervisor',
            field=models.CharField(max_length=250),
        ),
    ]
