# Generated by Django 4.2.11 on 2024-05-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_membership_alter_orders_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='material_costs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='owner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
