# Generated by Django 4.2.11 on 2024-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_material_costs_orders_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='material_costs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
