# Generated by Django 4.2.11 on 2024-03-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='gain',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='other',
            name='risk',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
