# Generated by Django 4.2.11 on 2024-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_alter_other_gain_alter_other_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='gain',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='other',
            name='risk',
            field=models.IntegerField(),
        ),
    ]
