# Generated by Django 4.2.11 on 2024-04-04 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrinters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('preparation_cost', models.FloatField()),
                ('start_up_cost', models.FloatField()),
                ('printer_wear_and_tear', models.IntegerField()),
                ('depreciation_in_hours', models.IntegerField()),
                ('courier_depreciation', models.FloatField()),
                ('inverter_and_battery_wear', models.IntegerField()),
                ('kilowatts_old', models.IntegerField()),
                ('price_per_kilowatt_with_depreciation', models.FloatField()),
                ('electricity_courier', models.FloatField()),
                ('electricity_costs', models.FloatField()),
                ('courier_printing', models.FloatField()),
                ('single_material', models.TextField(max_length=50)),
                ('termination_costs', models.FloatField()),
                ('supervision_costs', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
