# Generated by Django 4.2.11 on 2024-04-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_finance_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='user_id',
            new_name='user',
        ),
    ]
