version: '3.9'

services:
  api:
    build:
      dockerfile: /Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8050
    volumes:
      - backend:/code_api
      - media-volume:/code_api/media
    ports:
      - 8050:8050
    env_file:
      - .env

  procosts-mysql-db:
    container_name: procosts-mysql-db
    image: mariadb:10.4.24
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: printing_costs
    volumes:
      - mysql-storage:/var/lib/mysql
    ports:
      - "3306:3306"
 
  procosts-phpmyadmin:
    container_name: procosts-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    environment:
      PMA_HOST: procosts-mysql-db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8000:80"
      
volumes:
  backend:
  media-volume:
  mysql-storage: