version: '3.9'

services:
  
  procosts-mysql-db:
    container_name: procosts-mysql-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'printing_costs' 
      MYSQL_USER: 'admin' 
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password' 
    
    volumes:
      - mysql-storage:/var/lib/mysql
      - /tmp/app/mysqld:/var/run/mysqld
    ports:
      - "3308:3306"
    networks:
      - mynetwork
  
  api:
    container_name: api
    depends_on:
      - procosts-mysql-db
    build:
      dockerfile: /Dockerfile
    restart: unless-stopped
    command: python manage.py runserver localhost:8050
    volumes:
      - backend:/code_api
      - media-volume:/code_api/media
      - /tmp/app/mysqld:/run/mysqld
    ports:
      - 8050:8050
    environment:
      - DJANGO_SETTINGS_MODULE=procosts.settings
      - DATABASE_NAME=printing_costs
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=procosts-mysql-db
      - DATABASE_PORT=3308
    networks:
      - mynetwork

  
  procosts-phpmyadmin:
    container_name: procosts-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    environment:
      PMA_HOST: procosts-mysql-db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8000:80"
    networks:
      - mynetwork
      
volumes:
  backend:
  media-volume:
  mysql-storage:

networks:
  mynetwork:
