# Generated by Django 4.2.11 on 2024-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaterials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaterials',
            name='brand',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usermaterials',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
