# Generated by Django 4.2.11 on 2024-05-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermaterials', '0002_usermaterials_brand_usermaterials_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaterials',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
