# Generated by Django 4.2.11 on 2024-03-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('preparation_cost', models.DecimalField(decimal_places=10, max_digits=10)),
                ('start_up_cost', models.DecimalField(decimal_places=10, max_digits=10)),
                ('printer_wear_and_tear', models.IntegerField()),
                ('depreciation_in_hours', models.IntegerField()),
                ('courier_depreciation', models.DecimalField(decimal_places=10, max_digits=10)),
                ('inverter_and_battery_wear', models.IntegerField()),
                ('kilowatts_old', models.IntegerField()),
                ('price_per_kilowatt_with_depreciation', models.DecimalField(decimal_places=10, max_digits=10)),
                ('electricity_courier', models.DecimalField(decimal_places=10, max_digits=10)),
                ('electricity_costs', models.DecimalField(decimal_places=10, max_digits=10)),
                ('courier_printing', models.DecimalField(decimal_places=10, max_digits=10)),
                ('single_material', models.TextField(max_length=50)),
                ('termination_costs', models.DecimalField(decimal_places=10, max_digits=10)),
                ('supervision_costs', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
