# Generated by Django 4.2.11 on 2024-03-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='courier_depreciation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='printers',
            name='courier_printing',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='printers',
            name='electricity_costs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='printers',
            name='electricity_courier',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='printers',
            name='preparation_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='printers',
            name='price_per_kilowatt_with_depreciation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='printers',
            name='start_up_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='printers',
            name='supervision_costs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='printers',
            name='termination_costs',
            field=models.FloatField(),
        ),
    ]
