# Generated by Django 4.2.11 on 2024-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_materials_cost_per_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='brand',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
